# Generated by Django 5.0.7 on 2024-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familyasi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='hodimlar')),
                ('mansabi', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('kirirtilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilagan_sana', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
